### PR TITLE
Retry on 500 errors

### PR DESCRIPTION
**Pull request by emschwartz**

### CODE REVIEW

**Comment by calvinfo** [comment]
Thanks!

**Comment by mderazon** [comment]
@calvinfo can you please publish this ?

**Comment by calvinfo** [comment]
done!

**Comment by mderazon** [comment]
Are you sure you published to npm ? I still see v0.5.1 as the latest

**Comment by calvinfo** [comment]
Whoop, done!

**Comment by mderazon** [comment]
Thanks!

**Pull request merged**
