### PR TITLE
fix: retry not work in browser

### PR DESCRIPTION
**Pull request by alekzonder**
tested with superagent 1.7.2

testid in last chrome, safari, firefox, opera, ie9, ie10, ie11

### CODE REVIEW

**Comment by fullfs** [comment]
Hey! Looks like the PR will fix the error I'm facing:
`Uncaught TypeError: Cannot read property '_headers' of undefined`
It's very annoying. Any hope the PR could be merged?

**Comment by sulldiggs** [comment]
Any word on this pull request? I find myself having the same issue.

@fullfs @alekzonder - Did either of you find a related solution to your problem?

**Comment by alekzonder** [comment]
@sulldiggs commit in pull request fix this problem, but pull request created in January and has no any reaction from contributors

You can try to use my fork 

https://github.com/alekzonder/superagent-retry/tree/fix-retry-in-browser

**Comment by niftylettuce** [comment]
Can you re-open this @alekzonder

**Comment by niftylettuce** [comment]
Nevermind, the latest version of `superagent` has built-in support for a `retry` method <https://visionmedia.github.io/superagent/#retrying-requests>

**Pull request closed without merging**
