### PR TITLE
Retry on user defined errors. Delay retries

### PR DESCRIPTION
**Pull request by Edgpaez**
This PR does two things:
1. It allows the user to provide a callback to indicate that a request has to be retried
2. It allows the user to wait before retrying

I know this doesn't sound like the "usual" scenario but I wanted to have the code out there so that people could find it. If you guys find it useful I can split it in two PRs

I've had to use it many times in scenarios when client's APIs don't consistently return 200 and when I know I have to wait before their autoscaling kicks in. I know it's not ideal, but some things are simply out of your control.

Thanks for this library BTW!

### CODE REVIEW

**Comment by marcovdkuur** [comment]
This is also a feature we are looking for, would be great if it could be merged :-)

**Comment by erikbaan** [comment]
+1

**Comment by janvenhuis** [comment]
Merging this feature would be awesome!

**Comment by Redsandro** [comment]
@Edgpaez Can we delay only specific errors with this?

**Comment by Edgpaez** [comment]
@Redsandro You mean only delaying some errors but retrying right away others? You can't do that now, no :( 
This only allows you to specify a delay for ALL retries (even the user defined ones).

**Pull request closed without merging**
